"use client";

import { useState, useRef, useEffect } from "react";
import { cn } from "@/lib/utils";
import { Home, CheckCircle2, Flower2, ListTodo, Settings, Check, Plus, Wrench, FileText, BookOpen, Grid3x3, Send, Sparkles, Target, Flame, ArrowRight } from "lucide-react";

type Page = "dashboard" | "habits" | "mindfulness" | "tasks" | "noor" | "notes" | "documents" | "grid";
const navItems = [{id:"dashboard" as Page,icon:Home,label:"Dashboard"},{id:"habits" as Page,icon:CheckCircle2,label:"Habits"},{id:"mindfulness" as Page,icon:Flower2,label:"Mindfulness"},{id:"tasks" as Page,icon:ListTodo,label:"Tasks"},{id:"noor" as Page,icon:Sparkles,label:"Noor"}];
const toolItems = [{id:"notes" as Page,icon:FileText,label:"Notes"},{id:"documents" as Page,icon:BookOpen,label:"Documents"},{id:"grid" as Page,icon:Grid3x3,label:"Grid"}];
const mh = [{name:"Morning walk",streak:12,done:false,emoji:"\u{1F6B6}"},{name:"Read 10 pages",streak:7,done:true,emoji:"\u{1F4D6}"},{name:"Drink water",streak:23,done:false,emoji:"\u{1F4A7}"},{name:"Meditate",streak:5,done:false,emoji:"\u{1F9D8}"},{name:"Journal",streak:3,done:false,emoji:"\u{1F4DD}"}];
const mt = [{title:"Plan weekend trip",done:true,priority:"normal"},{title:"Call dentist",done:true,priority:"normal"},{title:"Read 30 minutes",done:false,priority:"normal"},{title:"Grocery shopping",done:false,priority:"urgent"},{title:"Email teacher",done:false,priority:"normal"}];
const mn = [{title:"Project ideas",preview:"Build something amazing today...",time:"2h ago"},{title:"Shopping list",preview:"Milk, eggs, butter, bread",time:"1d ago"},{title:"Journal entry",preview:"Today was a great day because...",time:"3d ago"}];
const nr: Record<string,string> = {default:"Hey! I am Noor. Ask me anything about your day!",habits:"Your morning walk streak is at 12 days. Keep it going!",help:"I can help with goals, habits, journaling, tasks, or just chatting!",plan:"Quick plan: 1) Morning walk, 2) Read, 3) Complete top 3 tasks."};
export function OrleiaInteractivePreview() {
  const [ap,setAp]=useState<Page>("dashboard");
  const [hab,setHab]=useState(mh);
  const [ci,setCi]=useState("");
  const [cm,setCm]=useState<{role:"user"|"noor";text:string}[]>([{role:"noor",text:nr.default}]);
  const [typing,setTyping]=useState(false);
  const [toolsOpen,setToolsOpen]=useState(true);
  const endRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[cm]);
  const tog=(i:number)=>setHab(p=>p.map((h,j)=>j===i?{...h,done:!h.done}:h));
  const send=()=>{if(!ci.trim())return;const m=ci.trim().toLowerCase();setCm(p=>[...p,{role:"user",text:ci}]);setCi("");setTyping(true);setTimeout(()=>{let r=nr.default;if(m.includes("habit"))r=nr.habits;else if(m.includes("help"))r=nr.help;else if(m.includes("plan")||m.includes("today"))r=nr.plan;else r="Focus on habits! You are on a "+hab[0].streak+"-day streak!";setCm(p=>[...p,{role:"noor",text:r}]);setTyping(false);},1200);};
  const dn=hab.filter(h=>h.done).length;
  const tn=mt.filter(t=>t.done).length;
  const NI=({id,icon:Icon,label}:{id:Page;icon:React.ComponentType<{className?:string}>;label:string})=>(<button onClick={()=>setAp(id)} className={cn("group flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-all w-full text-left",ap===id?"bg-primary/10 text-primary":"text-muted-foreground/60 hover:text-muted-foreground hover:bg-sidebar-hover")}><Icon className="h-5 w-5 shrink-0"/><span>{label}</span></button>);
  const TI=({id,icon:Icon,label}:{id:Page;icon:React.ComponentType<{className?:string}>;label:string})=>(<button onClick={()=>setAp(id)} className={cn("group flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-xs font-medium w-full text-left",ap===id?"bg-primary/10 text-primary":"text-muted-foreground/60 hover:text-muted-foreground hover:bg-sidebar-hover")}><Icon className="h-5 w-5 shrink-0"/><span>{label}</span></button>);
  return(
    <div className="w-full max-w-5xl mx-auto">
      <div className="rounded-2xl border border-border bg-background shadow-2xl overflow-hidden">
        <div className="flex items-center gap-2 px-4 py-2.5 bg-sidebar border-b border-border">
          <div className="flex gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-red-500/70"/><div className="w-2.5 h-2.5 rounded-full bg-yellow-500/70"/><div className="w-2.5 h-2.5 rounded-full bg-green-500/70"/></div>
          <div className="flex-1 text-center"><span className="text-[10px] text-muted-foreground font-medium tracking-wider uppercase">Orleia</span></div>
          <div className="w-[46px]"/>
        </div>
        <div className="flex h-[420px] md:h-[480px]">
          <div className="hidden md:flex w-60 flex-col border-r border-border bg-sidebar p-3">
            <div className="flex items-center gap-2 px-3 mb-4"><Sparkles className="h-5 w-5 text-primary"/><span className="text-sm font-bold tracking-wider text-foreground">ORLEIA</span></div>
            <div className="space-y-0.5 mb-4">{navItems.map(i=><NI key={i.id} {...i}/>)}</div>
            <button onClick={()=>setToolsOpen(!toolsOpen)} className="flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-xs font-medium text-muted-foreground/50 transition-all hover:text-muted-foreground"><Wrench className="h-5 w-5 shrink-0"/><span className="flex-1 text-left">Tools</span></button>
            {toolsOpen&&<div className="space-y-0.5">{toolItems.map(i=><TI key={i.id} {...i}/>)}</div>}
            <div className="mt-auto border-t border-border pt-3">
              <button className="flex items-center gap-2.5 w-full rounded-lg px-2.5 py-2 text-xs text-muted-foreground/60 hover:text-foreground hover:bg-sidebar-hover transition-all"><Settings className="h-3.5 w-3.5"/><span>Settings</span></button>
            </div>
          </div>
          <div className="flex-1 overflow-auto bg-background">
            {ap==="dashboard"&&(<div className="p-6 space-y-6"><div><h1 className="text-3xl font-bold mb-1">Good evening!</h1><p className="text-sm text-muted-foreground">Here is what is happening today.</p></div><div className="grid grid-cols-2 gap-3">{[{l:"Habits today",v:`${dn}/${hab.length}`,i:CheckCircle2},{l:"Tasks today",v:`${tn}/${mt.length}`,i:Target},{l:"Journal streak",v:"3d",i:Flame},{l:"Notes",v:"3",i:FileText}].map(s=>(<div key={s.l} className="card"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-muted"><s.i className="h-5 w-5 text-primary"/></div><p className="mt-3 text-2xl font-bold">{s.v}</p><p className="text-sm text-muted-foreground mt-1">{s.l}</p></div>))}</div><div className="card"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-muted-foreground"/><h3 className="text-sm font-semibold">Habits today</h3></div><button onClick={()=>setAp("habits")} className="text-xs text-primary hover:text-primary flex items-center gap-1">View all <ArrowRight className="h-3 w-3"/></button></div><div className="space-y-1.5">{hab.slice(0,4).map((h,i)=>(<div key={i} className="flex items-center gap-2.5 rounded-lg px-2 py-1.5 hover:bg-secondary transition-colors"><button onClick={()=>tog(i)} className={cn("flex h-5 w-5 shrink-0 items-center justify-center rounded-full border transition-all",h.done?"bg-primary border-primary text-white":"border-muted-foreground/30 hover:border-muted-foreground/60")}>{h.done&&<CheckCircle2 className="h-3 w-3"/>}</button><span className={cn("text-sm",h.done&&"line-through text-muted-foreground")}>{h.name}</span></div>))}</div></div><div className="card"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-muted-foreground"/><h3 className="text-sm font-semibold">Tasks today</h3></div><button onClick={()=>setAp("tasks")} className="text-xs text-primary hover:text-primary flex items-center gap-1">View all <ArrowRight className="h-3 w-3"/></button></div><div className="space-y-1.5">{mt.slice(0,4).map((t,i)=>(<div key={i} className="flex items-center gap-2.5 rounded-lg px-2 py-1.5 hover:bg-secondary transition-colors"><div className={cn("flex h-5 w-5 shrink-0 items-center justify-center rounded border",t.done?"bg-primary border-primary":"border-muted-foreground/30")}>{t.done&&<span className="text-white text-xs">{"\u2713"}</span>}</div><span className={cn("text-sm truncate",t.done&&"line-through text-muted-foreground")}>{t.title}</span>{t.priority==="urgent"&&<span className="tag bg-muted text-muted-foreground text-[10px]">!</span>}</div>))}</div></div></div>)}
            {ap==="habits"&&(<div className="relative space-y-6 p-6"><div className="flex items-start justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Habits</h1><p className="text-sm text-muted-foreground mt-2">Build streaks, build yourself.</p></div><button className="btn-primary flex items-center gap-2 shrink-0"><Plus className="h-4 w-4"/><span className="hidden sm:inline">New Habit</span></button></div><div className="grid gap-3">{hab.map((h,i)=>(<button key={i} onClick={()=>tog(i)} className={cn("card flex items-center gap-4 text-left transition-all",h.done&&"bg-primary/5 border-primary/20")}><div className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 transition-all",h.done?"bg-primary border-primary text-white":"border-muted-foreground/30")}>{h.done?<CheckCircle2 className="h-5 w-5"/>:<span className="text-lg">{h.emoji}</span>}</div><div className="flex-1 min-w-0"><p className={cn("text-sm font-medium",h.done&&"line-through text-muted-foreground")}>{h.name}</p><div className="flex items-center gap-2 mt-1"><Flame className="h-3 w-3 text-orange-500"/><span className="text-xs text-muted-foreground">{h.streak} day streak</span></div></div></button>))}</div></div>)}
            {ap==="mindfulness"&&(<div className="p-6 flex items-center justify-center h-full"><div className="text-center"><Flower2 className="w-16 h-16 text-muted-foreground/20 mx-auto mb-4"/><h2 className="text-xl font-bold text-foreground mb-2">Mindfulness</h2><p className="text-sm text-muted-foreground/60 max-w-xs">Journal, breathe, reflect. Your space for inner peace.</p></div></div>)}
            {ap==="tasks"&&(<div className="relative space-y-6 p-6"><div className="flex items-start justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Tasks</h1><p className="text-sm text-muted-foreground mt-2">Stay on track with your goals.</p></div><button className="btn-primary flex items-center gap-2 shrink-0"><Plus className="h-4 w-4"/><span className="hidden sm:inline">New Task</span></button></div><div className="space-y-1.5">{mt.map((t,i)=>(<div key={i} className="card flex items-center gap-3"><div className={cn("flex h-5 w-5 shrink-0 items-center justify-center rounded border",t.done?"bg-primary border-primary":"border-muted-foreground/30")}>{t.done&&<span className="text-white text-xs">{"\u2713"}</span>}</div><span className={cn("text-sm flex-1",t.done&&"line-through text-muted-foreground")}>{t.title}</span>{t.priority==="urgent"&&<span className="tag bg-muted text-muted-foreground text-[10px]">!</span>}</div>))}</div></div>)}
            {ap==="noor"&&(<div className="flex flex-col h-full"><div className="px-5 py-3 border-b border-border flex items-center gap-2"><div className="w-2 h-2 rounded-full bg-primary animate-pulse"/><span className="text-sm font-medium text-foreground">Noor</span><span className="text-[10px] text-muted-foreground">{"\u00B7 Ethos 4.7"}</span></div><div className="flex-1 overflow-y-auto p-5 space-y-3">{cm.map((m,i)=>(<div key={i} className={cn("flex",m.role==="user"?"justify-end":"justify-start")}><div className={cn("max-w-[80%] rounded-2xl px-3.5 py-2 text-xs leading-relaxed",m.role==="user"?"bg-primary/10 text-foreground rounded-br-md":"bg-card border border-border text-muted-foreground rounded-bl-md")}>{m.text}</div></div>))}{typing&&(<div className="flex justify-start"><div className="bg-card border border-border rounded-2xl rounded-bl-md px-3.5 py-2.5"><div className="flex gap-1"><div className="w-1.5 h-1.5 rounded-full bg-primary/60 animate-bounce"/><div className="w-1.5 h-1.5 rounded-full bg-primary/60 animate-bounce" style={{animationDelay:"150ms"}}/><div className="w-1.5 h-1.5 rounded-full bg-primary/60 animate-bounce" style={{animationDelay:"300ms"}}/></div></div></div>)}<div ref={endRef}/></div><div className="p-3 border-t border-border"><div className="flex items-center gap-2 bg-card border border-border rounded-xl px-3 py-2"><input value={ci} onChange={e=>setCi(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask Noor anything..." className="flex-1 bg-transparent text-xs text-foreground placeholder:text-muted-foreground/40 outline-none"/><button onClick={send} className="w-6 h-6 rounded-lg bg-primary/10 flex items-center justify-center hover:bg-primary/20 transition-all"><Send className="w-3 h-3 text-primary"/></button></div></div></div>)}
            {ap==="notes"&&(<div className="p-6"><div className="flex items-start justify-between mb-6"><div><h1 className="text-3xl font-bold tracking-tight">Notes</h1><p className="text-sm text-muted-foreground mt-2">Your thoughts, organized.</p></div><button className="btn-primary flex items-center gap-2 shrink-0"><Plus className="h-4 w-4"/><span className="hidden sm:inline">New Note</span></button></div><div className="space-y-2">{mn.map((n,i)=>(<div key={i} className="card hover:border-border/80 transition-all cursor-pointer"><div className="flex items-center justify-between mb-1"><span className="text-sm font-medium text-foreground">{n.title}</span><span className="text-[10px] text-muted-foreground/50">{n.time}</span></div><p className="text-xs text-muted-foreground truncate">{n.preview}</p></div>))}</div></div>)}
            {(ap==="documents"||ap==="grid")&&(<div className="p-6 flex items-center justify-center h-full"><div className="text-center"><p className="text-sm text-muted-foreground/50">{ap==="documents"?"Rich-text documents":"Spreadsheets"}</p><p className="text-xs text-muted-foreground/30 mt-1">Available in the full app</p></div></div>)}
          </div>
        </div>
      </div>
    </div>
  );
}
